package sniffer_redes;

import com.sun.awt.AWTUtilities;
import java.awt.Shape;
import java.awt.geom.RoundRectangle2D;
import javax.swing.JOptionPane;

public class Menu_Captura extends javax.swing.JFrame {

    public Menu_Captura() {
        initComponents();
         this.setLocationRelativeTo(null);
        Shape forma = new RoundRectangle2D.Double(0, 0, this.getBounds().width, this.getBounds().height, 30, 30);
        AWTUtilities.setWindowShape(this, forma);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        rbtnVuelo = new javax.swing.JRadioButton();
        rbtnArchivo = new javax.swing.JRadioButton();
        btnIr = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(25, 25, 112));
        jLabel2.setText("¿De qué forma desea analizar?");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 240, -1));

        buttonGroup1.add(rbtnVuelo);
        rbtnVuelo.setFont(new java.awt.Font("Meiryo UI", 1, 12)); // NOI18N
        rbtnVuelo.setForeground(new java.awt.Color(25, 25, 112));
        rbtnVuelo.setText("Tráfico al vuelo");
        getContentPane().add(rbtnVuelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        buttonGroup1.add(rbtnArchivo);
        rbtnArchivo.setFont(new java.awt.Font("Meiryo UI", 1, 12)); // NOI18N
        rbtnArchivo.setForeground(new java.awt.Color(25, 25, 112));
        rbtnArchivo.setText("Desde archivo .pcap");
        getContentPane().add(rbtnArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        btnIr.setText("IR !");
        btnIr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIrActionPerformed(evt);
            }
        });
        getContentPane().add(btnIr, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sniffer_redes/Fondo.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 170));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIrActionPerformed
        if(rbtnArchivo.isSelected()) {
            /* Código de Archivo */ 
            Analisis_Archivo aa = new Analisis_Archivo();
            aa.setVisible(true);
            this.dispose();
        } else if(rbtnVuelo.isSelected()) {
            /* Código de Vuelo */
            Analisis_Live al = new Analisis_Live();
            al.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar alguna opción.",
                ".:: ERROR ::.", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnIrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Captura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Captura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Captura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Captura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Captura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIr;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton rbtnArchivo;
    private javax.swing.JRadioButton rbtnVuelo;
    // End of variables declaration//GEN-END:variables
}
